image.type: jpg gif png
flash.type: swf
movie.type: mov avi wmv
rm.type: rm rmvb
plain.type: txt ini inf html htm rb jsp php asp
office.type: doc dot xls xla ppt pps ppz pot hlp chm ods
word.type: doc dot
excel.type: xls xla ods
ppt.type: ppt pps ppz pot
help.type: hlp chm
none.type: rar zip
resources.url: /files
resources.path: <%= ::Rails.root.to_s %>/public/files
encoding.to: UTF-8
encoding.from: UTF-8
temp.dir:
